language: python
python:
- '3.7'
addons:
  apt:
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev

install:
- pip install pytest-cov
- pip install delegator.py
- pip install -e git://github.com/phanrahan/magma.git@named-temporary-values#egg=magma
- pip install -e git://github.com/leonardt/fault.git@magma-rm-port#egg=fault
- pip install -e .
script:
- "./scripts/run_tests.sh"
deploy:
  provider: script
  script: /bin/bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
